### **Numpy**

In [84]:
# Numpy is an multi-dimentional array library where we can use numpy to store all sorts of data in 1D,2D,3D,4D etc.
# Numpy is very fast
# Numpy uses fixed type
# Faster to read less bytes of memory
# No type checking
# Numpy uses contaguous memory

## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

In [2]:
# Lists - Doesn't allow us to multiply the elements

a = [1,2,3]
b = [4,5,6]

a * b

TypeError: can't multiply sequence by non-int of type 'list'

In [3]:
# Numpy Array

import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])

a * b

array([ 4, 10, 18])

### **Numpy Applications**

In [4]:
# Mathematics (Matlab)
# Plotting (Matplotlib)
# Backend (Pandas)
# Machine Learning

### **The Basics**

In [5]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [8]:
b = np.array([[1.2,2.3,3.3],[1.5,3.0,9.0]])
b

array([[1.2, 2.3, 3.3],
       [1.5, 3. , 9. ]])

In [9]:
# Get Dimension

print(a.ndim)
print(b.ndim)

1
2


In [10]:
# Get Shape

print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [12]:
# Get Type

print(a.dtype)
print(b.dtype)

int32
float64


In [13]:
# Get Size

a.itemsize

4

In [16]:
# Total Size

print(a.size * a.itemsize)

print(a.nbytes)

12
12


### **Accessing/Changing specific elements, rows, columns, etc**

In [17]:
a = np.array([[1,2,3,4,5,6,7,8],[9,6,5,3,2,4,5,6]])
a

array([[1, 2, 3, 4, 5, 6, 7, 8],
       [9, 6, 5, 3, 2, 4, 5, 6]])

In [18]:
a.ndim

2

In [19]:
a.shape

(2, 8)

In [24]:
# Get a specific element [r, c]

print(a[1,1])
print(a[1,7])
print(a[0,7])
print(a[0,2])
print(a[0,-1])
print(a[-2,0])

6
6
8
3
8
1


In [25]:
# Get a specific row

print(a[0, :])
print(a[1, :])

[1 2 3 4 5 6 7 8]
[9 6 5 3 2 4 5 6]


In [26]:
# Get a specific column

print(a[:,0])
print(a[:,1])

[1 9]
[2 6]


In [28]:
# Changing particular element

a[0,1] = 11
print(a[0, :])

[ 1 11  3  4  5  6  7  8]


### **3D**

In [32]:
a = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
a

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [33]:
a.shape

(1, 3, 3)

In [37]:
# Get specific element

print(a[0,0,0])
print(a[0,0,2])
print(a[0,2,2])

1
3
9


### **Initializing Different Types Of Array**

In [39]:
# All 0's matrix

np.zeros(2)

array([0., 0.])

In [40]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [41]:
np.zeros((2,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [42]:
# All 1's matrix

np.ones(2)

array([1., 1.])

In [43]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [44]:
np.ones((2,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [45]:
np.ones((2,2,2,2))

array([[[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]]])

In [46]:
# Any other number

np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [49]:
np.full((2,2),99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [51]:
# Any other number (Full Like)

np.full_like(a,5)

array([[[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]]])

In [52]:
# Random decimal numbers

np.random.rand(4,4)

array([[0.52647805, 0.14585239, 0.14668056, 0.80893682],
       [0.35434458, 0.51035448, 0.79910725, 0.47992466],
       [0.7397062 , 0.2083282 , 0.45800174, 0.41768439],
       [0.03775062, 0.90635403, 0.5859184 , 0.78609414]])

In [53]:
np.random.rand(2,3,2)

array([[[0.31378144, 0.52206732],
        [0.03312862, 0.31671138],
        [0.26345712, 0.58343455]],

       [[0.64222839, 0.95085205],
        [0.49452778, 0.13349785],
        [0.51493518, 0.44668023]]])

In [55]:
# Random Shape

np.random.random_sample(a.shape)

array([[[0.7272116 , 0.83085114, 0.08283325],
        [0.68810757, 0.10121688, 0.31331146],
        [0.5870647 , 0.60539406, 0.06082147]]])

In [56]:
# Random Integer

np.random.randint(7)

4

In [58]:
np.random.randint(9, size=(3,3))

array([[5, 4, 3],
       [2, 3, 7],
       [7, 6, 7]])

In [59]:
np.random.randint(1,5,size=(4,4))

array([[3, 3, 4, 2],
       [3, 2, 3, 1],
       [1, 2, 2, 1],
       [1, 3, 3, 4]])

In [60]:
# Identity matrix

np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [61]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [62]:
# repeating array

arr = np.array([1,2,3])
r1 = np.repeat(arr,3)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [64]:
arr1 = np.array([[1,2,3]])
r2 = np.repeat(arr1,3,axis=0)
r2

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [66]:
# Copy()

a = np.array([1,2,3])
b = a.copy()
print(a)
b[0] = 111
print(b)

[1 2 3]
[111   2   3]


### **Mathematics**

In [68]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [69]:
a + 2

array([3, 4, 5])

In [70]:
a - 2

array([-1,  0,  1])

In [71]:
a * 3

array([3, 6, 9])

In [72]:
a % 3

array([1, 2, 0], dtype=int32)

In [74]:
a = np.array([2,2])
a ** 2

array([4, 4], dtype=int32)

In [75]:
# take the Sin

np.sin(a)

array([0.90929743, 0.90929743])

In [76]:
np.cos(a)

array([-0.41614684, -0.41614684])

### **Linear Algebra**

In [80]:
a = np.ones((2,3))
print(a)

b = np.full((3,3),2)
print(b)

a * b # Error as the sizes are different

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2 2]
 [2 2 2]
 [2 2 2]]


ValueError: operands could not be broadcast together with shapes (2,3) (3,3) 

In [82]:
np.matmul(a,b)

array([[6., 6., 6.],
       [6., 6., 6.]])

In [83]:
# Find the determinant

c = np.identity(3)
np.linalg.det(c)

1.0

### **Statistics**

In [85]:
stats = np.array([1,2,3,2,3,9,2,3,44,5])
stats

array([ 1,  2,  3,  2,  3,  9,  2,  3, 44,  5])

In [86]:
stats.min()

1

In [87]:
stats.max()

44

In [88]:
stat = np.array([[3,4,2],[5,6,3]])
stat

array([[3, 4, 2],
       [5, 6, 3]])

In [89]:
stat.min()

2

In [90]:
stat.max()

6

In [94]:
stat.min(axis=0)

array([3, 4, 2])

In [95]:
stat.max(axis=1)

array([4, 6])

In [96]:
stat.sum()

23

In [97]:
stat.sum(axis=0)

array([ 8, 10,  5])

In [98]:
stat.sum(axis=1)

array([ 9, 14])

### **Reorganizing Arrays**

In [100]:
bef = np.array([[1,2,3,4],[5,6,7,8]])
bef

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [103]:
afr = bef.reshape((4,2))
afr

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

### **Vertically Stacked Array**

In [105]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

v3 = np.stack([v1,v2])
print(v3)

v4 = np.stack([v1,v1,v2,v2,v1])
print(v4)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]
 [1 2 3 4]]


### **Horizontal Stack**

In [107]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

print(h1)
print()
print(h2)

h3 = np.hstack((h1,h2))
print(h3)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[0. 0.]
 [0. 0.]]
[[1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0.]]


### **Loading Data From File**

In [127]:
filedata = np.genfromtxt('text_data.txt', delimiter=',')
filedata

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19., 20., 21.]])

In [128]:
filedata.astype('int')

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21]])

### **Boolean Masking & Advance Indexing**

In [129]:
filedata > 10

array([[False, False, False, False, False, False, False],
       [False, False, False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])

In [131]:
filedata[filedata > 10]

array([11., 12., 13., 14., 15., 16., 17., 18., 19., 20., 21.])

In [133]:
np.any(filedata > 10, axis=1)

array([False,  True,  True])

In [136]:
((filedata >10) & (filedata < 100))

array([[False, False, False, False, False, False, False],
       [False, False, False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])

In [137]:
(~((filedata >10) & (filedata < 100)))

array([[ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True, False, False, False, False],
       [False, False, False, False, False, False, False]])