### Numpy Array - Basic Operations

In [1]:
import numpy as np
np.array(['Sen',2,3])


array(['Sen', '2', '3'], dtype='<U3')

In [2]:
print(type(np.array(['Sen',2,3])))

<class 'numpy.ndarray'>


In [3]:
# Upcasting

np.array([1,2,3.0])

array([1., 2., 3.])

In [7]:
# 2D Array

import numpy as np
arr = np.array([[1,2],[2,3]])
print(arr)
print()
print(arr.ndim)
print(arr.shape)

[[1 2]
 [2 3]]

2
(2, 2)


In [11]:
# Dimention Change

import numpy as np
arr = np.array([1,2,3,4],ndmin=5)
print(arr)
print(arr.ndim)

[[[[[1 2 3 4]]]]]
5


In [13]:
# DataType Change

import numpy as np
arr1 = np.array([1,2,3],dtype=complex)
print(arr1)
print(arr1.dtype)

[1.+0.j 2.+0.j 3.+0.j]
complex128


In [17]:
#Data-type consisting of more than one element:

arr2 = np.array([[1,2],[3,4]],dtype=[('a','<i2'),('b','<i8')])
print(arr2)
print(arr2.dtype)

[[(1, 1) (2, 2)]
 [(3, 3) (4, 4)]]
[('a', '<i2'), ('b', '<i8')]


In [18]:
print(arr2[0])
print(arr2[1])
print(arr2[0,0])
print(arr2[0,1])
print(arr2[1,0])
print(arr2[1,1])

[(1, 1) (2, 2)]
[(3, 3) (4, 4)]
(1, 1)
(2, 2)
(3, 3)
(4, 4)


In [19]:
# Creating array from subclass

arr = np.mat(np.array([[1,2],[4,7]]))
arr

matrix([[1, 2],
        [4, 7]])

In [21]:
np.mat(['1,2;3,4'])

matrix([['1,2;3,4']], dtype='<U7')

### Numpy.asarray

In [22]:
l = [1,2,3,4]
print(l)
print(type(l))

[1, 2, 3, 4]
<class 'list'>


In [24]:
arr = np.asarray(l)
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


### Numpy Copy

In [25]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [26]:
b = np.array(a,copy=True)
print(b)
print(type(b))

[1 2 3]
<class 'numpy.ndarray'>


In [28]:
# Reference

x = np.array([1,2,3])
print(type(x))
print(id(x))
print(x)

<class 'numpy.ndarray'>
437380910176
[1 2 3]


In [29]:
y = x
print(y)
print(id(y))

[1 2 3]
437380910176


### Numpy.fromfunction

In [31]:
arr = np.fromfunction(lambda i,j:i == j,(3,3))
print(arr)

[[ True False False]
 [False  True False]
 [False False  True]]


In [40]:
arr1 = np.fromfunction(lambda i,j: i>j,(3,3),dtype=int)
arr1

array([[False, False, False],
       [ True, False, False],
       [ True,  True, False]])

In [47]:
# Creation of !d using Iterable

iterable = (x*x for x in range(10))
print(iterable)

<generator object <genexpr> at 0x00000065D5EEE4F8>


In [48]:
# np.fromiter(iterable,int)

In [49]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16., 25., 36., 49., 64., 81.])

In [52]:
# Textdata in a string

arr = np.fromstring('1 2 3 ',sep=' ')
print(arr)
print(type(arr))

[1. 2. 3.]
<class 'numpy.ndarray'>


In [53]:
arr2 = np.fromstring('1,2',sep=',')
print(arr2)
print(type(arr2))

[1. 2.]
<class 'numpy.ndarray'>


In [55]:
x1 = np.array([1,2,3,4])
x2 = np.array(['a','b','c','d'])
x3 = np.array([1.1,1.2,1.3,1.4])

x4 = np.core.records.fromarrays([x1,x2,x3])
x4

rec.array([(1, 'a', 1.1), (2, 'b', 1.2), (3, 'c', 1.3), (4, 'd', 1.4)],
          dtype=[('f0', '<i4'), ('f1', '<U1'), ('f2', '<f8')])

In [57]:
print(x4[0])
print(x4[1])
print(x4[2])
print(x4[3])

(1, 'a', 1.1)
(2, 'b', 1.2)
(3, 'c', 1.3)
(4, 'd', 1.4)


### Datatypes

In [58]:
list = [1,2,3,4]
import numpy as np
arr = np.array(list)
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [60]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
import numpy as np
mat = np.matrix(my_mat)


In [63]:
print('Matrix: ',mat)
print('Matrix Type: ',type(mat))
print('Matrix Dimension: ',mat.ndim)
print('Matrix Shape: ',mat.shape)
print('Matrix Size: ',mat.size)
print('Matrix Dtype: ',mat.dtype)

Matrix:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix Type:  <class 'numpy.matrix'>
Matrix Dimension:  2
Matrix Shape:  (3, 3)
Matrix Size:  9
Matrix Dtype:  int32


### Arange & Linspace

In [66]:
import numpy as np
arr = np.arange(1,10,2)
print(arr)
print(type(arr))

[1 3 5 7 9]
<class 'numpy.ndarray'>


In [67]:
import numpy as np
arr1 = np.arange(1,10,0.5)
print(arr1)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]


In [69]:
# Linearly spaced numbers

import numpy as np
lins = np.linspace(1,10,10)
print(lins)
print(type(lins))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
<class 'numpy.ndarray'>


In [70]:
import numpy as np
linsp = np.linspace(1,10,50)
print(linsp)

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


### Matrix Creation

In [73]:
print('Vectors of Zeros...\n')
print(np.zeros(5))
print(type(np.zeros(5)))

Vectors of Zeros...

[0. 0. 0. 0. 0.]
<class 'numpy.ndarray'>


In [75]:
print('Matrix of Zeroes: \n')
arr = np.zeros((5,4))
print(arr)
print(type(arr))

Matrix of Zeroes: 

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<class 'numpy.ndarray'>


In [76]:
print('Matrix of Ones: ')
ones = np.ones(3)
print(ones)
print(type(ones))

Matrix of Ones: 
[1. 1. 1.]
<class 'numpy.ndarray'>


In [77]:
print('Matrix of ones: ')
oness = np.ones((5,4))
print(oness)

Matrix of ones: 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [79]:
print('Matrix of ones: ')
one = np.ones((5,2,6))
print(one)
print()
print(one.size)
print(one.ndim)
print(one.shape)
print(one.dtype)

Matrix of ones: 
[[[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]]

60
3
(5, 2, 6)
float64


In [82]:
# Matrix of 6's

six = 5 + np.ones(3)
six

array([6., 6., 6.])

In [83]:
# Empty Matrix

import numpy as np
empty = np.empty((3,3))
print(empty)

[[ 1.  4.  9.]
 [16. 25. 36.]
 [49. 64. 81.]]


In [84]:
import numpy as np
emp = np.empty((5,5))
print(emp)

[[2.16075017e-312 7.55920438e-322 0.00000000e+000 0.00000000e+000
  2.14321575e-312]
 [1.15998412e-028 2.44171989e+232 8.00801729e+159 8.16124052e-153
  3.88834045e+160]
 [1.16304910e+214 6.12743486e-154 3.92880985e+160 5.36788256e+242
  9.92152605e+247]
 [6.01391519e-154 1.16310967e+214 9.92152605e+247 5.56206154e+180
  5.01201375e+217]
 [4.47303447e-143 6.32672819e+180 4.74483502e+170 5.65033340e-038
  8.34402698e-308]]


In [85]:
import numpy as np
emp2 = np.empty((2,2))
print(emp2)

[[1.1 1.2]
 [1.3 1.4]]


In [87]:
# Identity matrix

identity = np.eye(3,3)
print(identity)
print(type(identity))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
<class 'numpy.ndarray'>


In [88]:
id = np.eye(4,4)
print(id)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [89]:
np.arange(3)

array([0, 1, 2])

In [90]:
np.arange(3.0)

array([0., 1., 2.])

In [92]:
np.linspace(2.0,3.0,num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [93]:
np.linspace(1,10,num=5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [95]:
# Extract or Construct diagonal array

import numpy as np
x = np.arange(16).reshape(4,4)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [97]:
print(np.diag(x))

[ 0  5 10 15]


In [100]:
print(np.diag(x,k=2))

[2 7]


In [101]:
print(np.diag(x,k=1))

[ 1  6 11]


In [102]:
print(np.diag(x,k=0))

[ 0  5 10 15]


In [103]:
print(np.diag(x,k=3))

[3]


In [104]:
np.diag(np.diag(x))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

### Random Number Generation

In [105]:
from numpy import random
print(np.random.rand(2,3))

[[0.65101659 0.47737676 0.58696087]
 [0.52056719 0.88968316 0.36209053]]


In [106]:
print(np.random.rand(3,3))

[[0.52828125 0.18824829 0.33389964]
 [0.7988241  0.89950461 0.76688682]
 [0.30295146 0.47028787 0.11545881]]


In [107]:
print('Random Integer: ')
print(np.random.randint(0,10))

Random Integer: 
8


In [108]:
print(np.random.randint(0,100,(4,4)))

[[10 98 12 86]
 [71 96 33 91]
 [45 82 13 23]
 [27 12 89 11]]


In [109]:
print('Dice Sample for 20 times: ',np.random.randint(1,7,20))

Dice Sample for 20 times:  [3 2 5 3 6 2 1 1 2 3 6 1 5 2 2 6 5 3 1 4]


### Reshape

In [110]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.dtype)
print(arr.size)
print(arr.shape)
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
int32
6
(2, 3)
2


In [111]:
arr1 = arr.reshape(2,3)
print(arr1)
print(arr1.shape)
print(arr1.size)

[[1 2 3]
 [4 5 6]]
(2, 3)
6


In [116]:
from numpy.random import randint as ri
arr = ri(1,100,10)
print(arr)
print(sorted(arr))

[ 4 44  9 62 42 48 69 69 23 14]
[4, 9, 14, 23, 42, 44, 48, 62, 69, 69]


In [117]:
print(arr.max())
print(arr.min())

69
4


### Indexing & Slicing

In [119]:
arr = np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


In [120]:
print('Indexing: ')
print('arr[0]: ',arr[0])
print('arr[1]: ',arr[1])
print('arr[2]: ',arr[2])
print('arr[3]: ',arr[3])
print('arr[4]: ',arr[4])
print('arr[5]: ',arr[5])

Indexing: 
arr[0]:  1
arr[1]:  2
arr[2]:  3
arr[3]:  4
arr[4]:  5
arr[5]:  6


In [129]:
print('Slicing: ')
print('Positive Slicing: ')
print('arr[ : ] :',arr[ : ])
print('arr[:1] :',arr[ :1])
print('arr[:2] :',arr[ :2])
print('arr[:3] :',arr[ :3])
print('arr[:4] :',arr[ :4])
print('arr[:5] :',arr[ :5])
print()
print('Negative Slicing: ')
print('arr[-6:] :',arr[-6:])
print('arr[-6:-5] :',arr[-6:-5])
print('arr[-6:-4] :',arr[-6:-4])
print('arr[-6:-3] :',arr[-6:-3])
print('arr[-6:-2] :',arr[-6:-2])
print('arr[-6:-1] :',arr[-6:-1])
print('arr[-6:0] :',arr[-6:0])


Slicing: 
Positive Slicing: 
arr[ : ] : [1 2 3 4 5 6]
arr[:1] : [1]
arr[:2] : [1 2]
arr[:3] : [1 2 3]
arr[:4] : [1 2 3 4]
arr[:5] : [1 2 3 4 5]

Negative Slicing: 
arr[-6:] : [1 2 3 4 5 6]
arr[-6:-5] : [1]
arr[-6:-4] : [1 2]
arr[-6:-3] : [1 2 3]
arr[-6:-2] : [1 2 3 4]
arr[-6:-1] : [1 2 3 4 5]
arr[-6:0] : []


### Subsetting

In [130]:
import numpy as np
from numpy.random import randint

arr = ri(1,100,10).reshape(2,5)
arr

array([[76, 61, 18, 79, 53],
       [42, 41, 30, 62, 64]])

In [131]:
arr > 50

array([[ True,  True, False,  True,  True],
       [False, False, False,  True,  True]])

In [133]:
arr[arr>50]

array([76, 61, 79, 53, 62, 64])

### Universal Functions

In [140]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(11,20,9)).reshape(3,3)


In [141]:
mat1

array([[3, 2, 7],
       [7, 1, 1],
       [1, 8, 4]])

In [142]:
mat2

array([[15, 18, 13],
       [19, 16, 12],
       [14, 15, 18]])

In [143]:
mat3 = mat1 * mat2
mat3

array([[ 45,  36,  91],
       [133,  16,  12],
       [ 14, 120,  72]])

In [144]:
mat4 = mat1 + mat2
mat4

array([[18, 20, 20],
       [26, 17, 13],
       [15, 23, 22]])

In [145]:
print('Addition of Scaler Matrix: ')
print(100+mat1)

Addition of Scaler Matrix: 
[[103 102 107]
 [107 101 101]
 [101 108 104]]


In [147]:
print('Exponential of Matrix: ')
print(pow(mat1,1))
print()
print(pow(mat1,2))

Exponential of Matrix: 
[[3 2 7]
 [7 1 1]
 [1 8 4]]

[[ 9  4 49]
 [49  1  1]
 [ 1 64 16]]


### Broadcasting

In [148]:
arr = np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [151]:
one_d = np.ones((1,4))
one_d

array([[1., 1., 1., 1.]])

In [152]:
add = arr + one_d
add

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [159]:
add1 = np.array([[1,2,3]])
add1 = add1.T


In [160]:
add1

array([[1],
       [2],
       [3]])

In [162]:
arr2 = arr + add1
arr2

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])